INSERT INTO APP (ID, NAME, INSTALLED, STATE,VERSION,LATEST_VERSION, LAST_STATE_UPDATE)
VALUES
    (1, 'App1', FALSE, 'SCHEDULED', '1.0', '2.0', CURRENT_TIMESTAMP),
    (2, 'App2', FALSE, 'SCHEDULED','1.1','1.1', CURRENT_TIMESTAMP),
    (3, 'App3', FALSE, 'SCHEDULED','1.2','1.2', CURRENT_TIMESTAMP);
